<svelte:head>
    <title>Svesta | Home</title>
</svelte:head>
<div class="container lg:px-48">
    <h1 class="font-bold text-xl">Welcome ~</h1>
    <p>Have a good day!</p>
    <p>Powered by <a href="https://kit.svelte.dev">Svelte-Kit</a> and <a href="https://vercel.com">Vercel</a></p>
    <!-- <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Minima fugit quod repellendus totam molestiae nam nesciunt iusto ad praesentium quidem deleniti atque, necessitatibus accusamus eaque veritatis modi obcaecati nobis mollitia non dicta laboriosam ipsa beatae fugiat ut. Tenetur temporibus, vel nisi similique maiores tempora odit iste aperiam? Debitis numquam hic nobis? Voluptas, beatae commodi, magnam sunt vel omnis fugit eaque error eos aperiam veniam, minus dolore illo necessitatibus aut nam consequatur ut eveniet ipsum molestias nobis officia quam eius culpa. Autem odio soluta dignissimos consectetur ex excepturi non culpa? Vero non molestias quidem sapiente atque tempore totam vel temporibus nobis!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores harum dicta, culpa reiciendis asperiores accusantium qui ut quam quos ratione architecto nostrum dolor nobis nesciunt sapiente odio nulla dolore aliquid molestias iste voluptatem! Quae commodi at eius numquam architecto excepturi iure qui repellat tempora. Commodi, aspernatur amet, dolores laboriosam sunt quae excepturi sit doloremque soluta exercitationem sapiente! Eum explicabo consectetur dolore reiciendis dolores blanditiis animi maiores earum, praesentium eveniet, necessitatibus rerum id quo accusamus. Exercitationem, voluptas magnam. Odio recusandae quae velit iusto maiores error iure voluptatem, voluptates voluptas fuga, dicta quisquam? Dolores, libero quidem tempore commodi culpa blanditiis alias. Eos!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione cum itaque accusamus hic, dicta iste sapiente ea laboriosam at esse distinctio dolorem tempore molestiae modi similique totam. Incidunt quam cumque, in ut quaerat adipisci ipsam eos modi, vero rerum nisi! Praesentium explicabo minus tempore eius enim doloremque quaerat adipisci qui? Deleniti dolores nesciunt, pariatur unde nam obcaecati. Consectetur, in. Dolorum enim ut aperiam inventore veniam consectetur non neque, placeat beatae illum! Doloremque iure non voluptatum rerum error adipisci quidem odit saepe repudiandae nihil. Assumenda, culpa? Totam, voluptatibus dicta labore unde illo, deleniti id aspernatur ratione nam voluptatem quia, ut excepturi.</p>
    <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Unde architecto explicabo vero placeat reiciendis fugit atque voluptatibus quas ipsa aperiam dolorem accusamus accusantium laboriosam excepturi, exercitationem magnam rerum quasi, eum maxime necessitatibus non ullam similique sequi ratione! Necessitatibus laudantium, dolorum beatae recusandae corporis in! Cumque eveniet dolorem quia sapiente! Delectus excepturi harum sit beatae iure commodi? Eveniet alias corporis, cupiditate fuga asperiores est, molestiae at earum officia incidunt in laudantium tenetur doloribus beatae. Reiciendis recusandae nihil, ipsum quo dolorem harum tempora! Perferendis corrupti consequuntur iste illum aperiam quae ipsam, placeat vero architecto in obcaecati, maxime doloremque, rerum iusto. Repellat, nam.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi, cupiditate cumque non reprehenderit alias possimus esse sapiente laudantium! Reprehenderit consequuntur error tempora, impedit quis voluptas cum commodi inventore harum nobis aliquam quos rem incidunt laboriosam veniam nemo quasi eos! Iste nulla laudantium excepturi maxime ea nostrum in, dolorum delectus tempore explicabo, alias hic fugiat. Deserunt sunt explicabo non numquam est perferendis vel, quasi tenetur praesentium nemo ad sint dicta dolore libero at, amet quibusdam quidem animi temporibus incidunt nam commodi! Nihil possimus, alias soluta inventore, aliquam ullam et modi quaerat iusto dolorum asperiores in aspernatur, reprehenderit ipsam eligendi odio. Vero?</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt iure, inventore quia suscipit ut fugit odio blanditiis autem perferendis laborum fuga pariatur alias aliquam, corporis dolorem distinctio nihil ratione, obcaecati culpa dicta velit! Similique, deleniti! Quos quasi placeat fugiat ratione reprehenderit suscipit expedita nihil, architecto quas ducimus accusamus numquam laboriosam aperiam fuga magni totam corporis natus sapiente esse. Culpa optio porro explicabo a quis consequuntur, tempore ad nulla cum possimus vero est aperiam qui. Eius qui doloribus, ipsam ipsa architecto unde temporibus, a nobis sequi iure totam quaerat quos dolorem! Eligendi obcaecati consectetur cum impedit, quisquam facere officia fuga sed.</p> -->
</div>